# Drop all existing DC/DM triggers:
drop trigger if exists TR_Address_DC;
drop trigger if exists TR_Address_DM;
drop trigger if exists TR_BillingRun_DC;
drop trigger if exists TR_BillingRun_DM;
drop trigger if exists TR_BillingRunStatus_DC;
drop trigger if exists TR_BillingRunStatus_DM;
drop trigger if exists TR_Contact_DC;
drop trigger if exists TR_Contact_DM;
drop trigger if exists TR_County_DC;
drop trigger if exists TR_County_DM;
drop trigger if exists TR_Customer_DC;
drop trigger if exists TR_Customer_DM;
drop trigger if exists TR_CustomerStatus_DC;
drop trigger if exists TR_CustomerStatus_DM;
drop trigger if exists TR_InvoiceMeter_DC;
drop trigger if exists TR_InvoiceMeter_DM;
drop trigger if exists TR_Invoice_DC;
drop trigger if exists TR_Invoice_DM;
drop trigger if exists TR_MeterReading_DC;
drop trigger if exists TR_MeterReading_DM;
drop trigger if exists TR_Meter_DC;
drop trigger if exists TR_Meter_DM;
drop trigger if exists TR_InvoiceStatus_DC;
drop trigger if exists TR_InvoiceStatus_DM;
drop trigger if exists TR_MeterStatus_DC;
drop trigger if exists TR_MeterStatus_DM;
drop trigger if exists TR_MeterType_DC;
drop trigger if exists TR_MeterType_DM;
drop trigger if exists TR_Unit_DC;
drop trigger if exists TR_Unit_DM;
drop trigger if exists TR_User_DC;
drop trigger if exists TR_User_DM;
drop trigger if exists TR_UserStatus_DC;
drop trigger if exists TR_UserStatus_DM;
drop trigger if exists TR_UserType_DC;
drop trigger if exists TR_UserType_DM;
drop trigger if exists TR_MarketPrice_DC;
drop trigger if exists TR_MarketPrice_DM;
drop trigger if exists TR_MarketPriceType_DC;
drop trigger if exists TR_MarketPriceType_DM;
drop trigger if exists TR_EmailQueue_DC;
drop trigger if exists TR_EmailQueue_DM;

# Create all DC/DM triggers:
create trigger TR_Address_DC before insert on Address for each row set new.DateCreated = now();
create trigger TR_Address_DM before update on Address for each row set new.DateModified = now();
create trigger TR_BillingRun_DC before insert on BillingRun for each row set new.DateCreated = now();
create trigger TR_BillingRun_DM before update on BillingRun for each row set new.DateModified = now();
create trigger TR_BillingRunStatus_DC before insert on BillingRunStatus for each row set new.DateCreated = now();
create trigger TR_BillingRunStatus_DM before update on BillingRunStatus for each row set new.DateModified = now();
create trigger TR_Contact_DC before insert on Contact for each row set new.DateCreated = now();
create trigger TR_Contact_DM before update on Contact for each row set new.DateModified = now();
create trigger TR_County_DC before insert on County for each row set new.DateCreated = now();
create trigger TR_County_DM before update on County for each row set new.DateModified = now();
create trigger TR_Customer_DC before insert on Customer for each row set new.DateCreated = now();
create trigger TR_Customer_DM before update on Customer for each row set new.DateModified = now();
create trigger TR_CustomerStatus_DC before insert on CustomerStatus for each row set new.DateCreated = now();
create trigger TR_CustomerStatus_DM before update on CustomerStatus for each row set new.DateModified = now();
create trigger TR_InvoiceMeter_DC before insert on InvoiceMeter for each row set new.DateCreated = now();
create trigger TR_InvoiceMeter_DM before update on InvoiceMeter for each row set new.DateModified = now();
create trigger TR_Invoice_DC before insert on Invoice for each row set new.DateCreated = now();
create trigger TR_Invoice_DM before update on Invoice for each row set new.DateModified = now();
create trigger TR_MeterReading_DC before insert on MeterReading for each row set new.DateCreated = now();
create trigger TR_MeterReading_DM before update on MeterReading for each row set new.DateModified = now();
create trigger TR_Meter_DC before insert on Meter for each row set new.DateCreated = now();
create trigger TR_Meter_DM before update on Meter for each row set new.DateModified = now();
create trigger TR_InvoiceStatus_DC before insert on InvoiceStatus for each row set new.DateCreated = now();
create trigger TR_InvoiceStatus_DM before update on InvoiceStatus for each row set new.DateModified = now();
create trigger TR_MeterStatus_DC before insert on MeterStatus for each row set new.DateCreated = now();
create trigger TR_MeterStatus_DM before update on MeterStatus for each row set new.DateModified = now();
create trigger TR_MeterType_DC before insert on MeterType for each row set new.DateCreated = now();
create trigger TR_MeterType_DM before update on MeterType for each row set new.DateModified = now();
create trigger TR_Unit_DC before insert on Unit for each row set new.DateCreated = now();
create trigger TR_Unit_DM before update on Unit for each row set new.DateModified = now();
create trigger TR_User_DC before insert on `User` for each row set new.DateCreated = now();
create trigger TR_User_DM before update on `User` for each row set new.DateModified = now();
create trigger TR_UserStatus_DC before insert on UserStatus for each row set new.DateCreated = now();
create trigger TR_UserStatus_DM before update on UserStatus for each row set new.DateModified = now();
create trigger TR_UserType_DC before insert on UserType for each row set new.DateCreated = now();
create trigger TR_UserType_DM before update on UserType for each row set new.DateModified = now();
create trigger TR_MarketPrice_DC before insert on MarketPrice for each row set new.DateCreated = now();
create trigger TR_MarketPrice_DM before update on MarketPrice for each row set new.DateModified = now();
create trigger TR_MarketPriceType_DC before insert on MarketPriceType for each row set new.DateCreated = now();
create trigger TR_MarketPriceType_DM before update on MarketPriceType for each row set new.DateModified = now();
create trigger TR_EmailQueue_DC before insert on EmailQueue for each row set new.DateCreated = now();
create trigger TR_EmailQueue_DM before update on EmailQueue for each row set new.DateModified = now();
